# Generated by Django 5.0.2 on 2024-03-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_cat_id', models.IntegerField()),
                ('Pro_cat_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Pro_Name', models.CharField(max_length=100)),
                ('Pro_Brand', models.CharField(max_length=100)),
                ('Pro_Price', models.IntegerField()),
                ('Pro_Cat_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
